services:
  - type: web
    name: my-blog
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn my_blog.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "my-blog.onrender.com"
