# Generated by Django 4.2 on 2025-04-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='picture_url',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
